steps:
  # Step 1: Run tests
  test:
    image: golang:1.26.0-alpine
    commands:
      - go test -v ./...
    when:
      event:
        - pull_request
        - tag
        - push

  # Step 2: Security audit
  security:
    image: golang:1.26.0-alpine
    commands:
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - govulncheck ./...
    when:
      event:
        - pull_request
        - tag
        - push

  # Step 3: Build binary
  build:
    image: golang:1.26.0-alpine
    commands:
      - apk add --no-cache git
      - go build -ldflags="-s -w -X main.version=${CI_COMMIT_TAG:-dev}" -trimpath -o repull ./cmd/repull
      - ls -lh repull
    when:
      event:
        - pull_request
        - tag
        - push

  # Step 4: Auto-tag patch release on push to main
  auto-tag:
    image: alpine
    commands:
      - apk add --no-cache git
      - git fetch --tags
      - |
        if git tag --points-at HEAD | grep -q '^v'; then
          echo "HEAD already has a version tag, skipping"
          exit 0
        fi
      - |
        LATEST=$(git tag -l 'v*' | sed 's/^v//' | sort -t. -k1,1n -k2,2n -k3,3n | tail -n1)
        if [ -z "$LATEST" ]; then
          NEW_TAG="v0.1.0"
        else
          MAJOR=$(echo "$LATEST" | cut -d. -f1)
          MINOR=$(echo "$LATEST" | cut -d. -f2)
          PATCH=$(echo "$LATEST" | cut -d. -f3)
          PATCH=$((PATCH + 1))
          NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
        fi
        echo "Tagging $NEW_TAG"
        git tag -a "$NEW_TAG" -m "Auto-release $NEW_TAG"
        REPO_URL=$(echo "${CI_FORGE_URL}/${CI_REPO}.git" | sed 's|https://|https://token:'"${CI_FORGE_TOKEN}"'@|')
        git push "$REPO_URL" "$NEW_TAG"
    environment:
      CI_FORGE_TOKEN:
        from_secret: forgejo_token
    when:
      event:
        - push
      branch:
        - main

  # Step 5: Build and push Docker image on tag
  docker-release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: fanuelsen/repull
      dockerfile: Dockerfile
      platforms: linux/amd64
      build_args:
        VERSION: ${CI_COMMIT_TAG}
      tags:
        - latest
        - ${CI_COMMIT_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag

  # Step 6: Create Forgejo release with binary
  forgejo-release:
    image: woodpeckerci/plugin-release
    settings:
      base_url: ${CI_FORGE_URL}
      api_key:
        from_secret: forgejo_token
      files:
        - repull
      title: "Repull ${CI_COMMIT_TAG}"
      note: |
        ## Repull ${CI_COMMIT_TAG}

        ### Docker Image
        ```bash
        docker pull fanuelsen/repull:${CI_COMMIT_TAG}
        ```

        ### Binary
        Download `repull` from assets below.

        ### Install
        ```bash
        chmod +x repull
        sudo mv repull /usr/local/bin/repull
        ```
      checksum:
        - sha256
      file_exists: skip
    when:
      event:
        - tag
